import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  Briefcase,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Copy,
  Download,
  Eye,
  FileEdit,
  FileText,
  FolderOpen,
  Globe,
  GraduationCap,
  HelpCircle,
  History,
  KeyRound,
  Lightbulb,
  Link as LinkIcon,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MoreVertical,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Save,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Trash2,
  Undo2,
  Redo2,
  Upload,
  UserRound,
  Wand2,
  X,
  type LucideProps,
} from "lucide-react";

/**
 * Thin wrapper around lucide-react so call sites use a stable semantic
 * vocabulary (`<Icon name="library" />`) instead of importing individual
 * lucide components everywhere.
 */
const ICONS = {
  library: FolderOpen,
  "new-tailoring": Wand2,
  editor: FileEdit,
  settings: Settings,
  support: HelpCircle,
  "sign-out": LogOut,
  history: History,
  "ai-suggestion": Sparkles,
  check: Check,
  "check-circle": CheckCircle2,
  lightbulb: Lightbulb,
  save: Save,
  preview: Eye,
  download: Download,
  more: MoreVertical,
  plus: Plus,
  search: Search,
  delete: Trash2,
  duplicate: Copy,
  rename: Pencil,
  close: X,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  undo: Undo2,
  redo: Redo2,
  upload: Upload,
  document: FileText,
  experience: Briefcase,
  education: GraduationCap,
  certification: Award,
  link: LinkIcon,
  email: Mail,
  phone: Phone,
  location: MapPin,
  website: Globe,
  company: Building2,
  "api-key": KeyRound,
  verified: ShieldCheck,
  retry: RefreshCw,
  user: UserRound,
  spinner: Loader2,
  menu: Menu,
  warning: AlertTriangle,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({ name, className, ...props }: { name: IconName } & LucideProps) {
  const Component = ICONS[name];
  return <Component className={className} {...props} />;
}
